# ASCII-Font › http://patorjk.com/software/taag/#p=display&f=Slant&t=Phlow
# 
#      _____ _ __          _____      __  __  _
#     / ___/(_) /____     / ___/___  / /_/ /_(_)___  ____ ______
#     \__ \/ / __/ _ \    \__ \/ _ \/ __/ __/ / __ \/ __ `/ ___/
#    ___/ / / /_/  __/   ___/ /  __/ /_/ /_/ / / / / /_/ (__  )
#   /____/_/\__/\___/   /____/\___/\__/\__/_/_/ /_/\__, /____/
#                                                 /____/
#
# Title of your website
title: 'Le Corps de cadets 2920'

# The slogan describes your website and is used on homepage in <title> and other important places
slogan: 'Fierté et excellence'

# The description is used on homepage and in the footer to quickly describe your website. Use a maximum of 150 characters for SEO-purposes.
description: "Le site CC2920 est destiné à vous fournir une multitude d'informations concernant notre corps de cadets et les différentes activités qui y sont offertes."

# The credits show up in the includes/_footer.html 
credits: 'Géré via le répertoire <a href="https://github.com/CC2920/web/" target="_blank">CC2920 GitHub.com</a>'
# This is for the editing function in _/includes/improve_content
# Leave it empty if your site is not on GitHub/GitHub Pages
improve_content: https://github.com/CC2920/web/edit/contributions

# Main author of the website
# See > authors.yml
author: sinedbo

# This URL is the main address for absolute links. Don't include a slash at the end.
#
url: 'https://www.cc2920.ca'
baseurl: ''

# Logo size is 600x80 pixels
logo: "logo.png"
group_photo: "CC2920-20240511-37.JPG"

favicon-32x32: favicon-32x32.png

# ncollections_dir: content
collections:
  communications:
    output: true
  drafts:
    output: false
  historique:
    output: true
  information:
    output: true
  presentation:
    output: true
  ressources: 
    output: true
  prix: 
    output: true

# Plugins
plugins:
    - jekyll-gist
    - jekyll-paginate
    - jekyll-relative-links

relative_links:
  enabled:     true
  collections: true


#       ____              _             __  _
#      / __ \____ _____ _(_)___  ____ _/ /_(_)___  ____
#     / /_/ / __ `/ __ `/ / __ \/ __ `/ __/ / __ \/ __ \
#    / ____/ /_/ / /_/ / / / / / /_/ / /_/ / /_/ / / / /
#   /_/    \__,_/\__, /_/_/ /_/\__,_/\__/_/\____/_/ /_/
#               /____/
#
paginate: 5                      # Paginates all X entries
paginate_path: "blog/page:num"   # Pagination path › Important for blog page in /blog/ to work


# Theme works best with Kramdown (using the table of contents function)
markdown           : kramdown
permalink          : /:categories/:title/
highlight          : rouge
excerpt_separator  : "<!--more-->"
include            : ['.htaccess']
# Exclude these files from your production _site
exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - INSTALL.md
    - vendor


# The language setting is used in /includes/header.html for html-settings
language: 'fr'


# Used › default.html front-matter and compress.html
# Options › http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  ignore:
    envs: [development]


#
#       ____       ____            ____
#      / __ \___  / __/___ ___  __/ / /_
#     / / / / _ \/ /_/ __ `/ / / / / __/
#    / /_/ /  __/ __/ /_/ / /_/ / / /_
#   /_____/\___/_/  \__,_/\__,_/_/\__/
#
# Default Settings

defaults:
  -
    scope:
      path: '' 				# an empty string here means all files in the project
      type: 'pages'
    values:
      show_meta: false 	# Hide metadata for all pages
      comments: false
      author: sinedbo     # Default author for pages
  -
    scope:
      path: ''
      type: 'posts'
    values:
      show_meta: true   # Show metadata for all posts
      # sidebar:        # Possible values › left, right › by default there will be no sidebar
      comments: false
      author: sinedbo     # Default author for posts
  - 
    scope: 
      path: '_communications'
      type: 'communications'
    values:
      navigationKey: communications
      breadcrumb: true
      layout: 'page-side-navigation'
      subheadline: 'Communications'
      include-in-nav: true
      order:
        - messages.md
        - information.md
        - bulletin.md
        - calendrier.md
  -
    scope:
      path: '_historique'
      type: 'historique'
    values:
      navigationKey: historique
      breadcrumb: true
      layout: 'page-fullwidth'
      subheadline: 'Historique'
      header:
        image_fullwidth: 'musique-historique.jpeg'
  -
    scope:
      path: '_historique/notre-unite'
      type: 'historique'
    values:
      navigationKey: unite
      breadcrumb: true
      layout: 'page-collection-navigation'
      include-in-nav: true
      subheadline: 'Historique de notre unité'
      include-in-nav: true
  -
    scope:
      path: '_historique/commandants'
      type: 'historique'
    values:
      navigationKey: commandants
      breadcrumb: true
      layout: 'commandant'
      subheadline: 'Historique'
      title: 'Biographie'
  - 
    scope: 
      path: '_information'
      type: 'information'
    values:
      navigationKey: information
      breadcrumb: true
      layout: 'page-side-navigation'
      include-in-nav: true
      subheadline: 'Information'
      header:
        image_fullwidth: 'cc2920-2018-06-24.jpg'
  - 
    scope: 
      path: '_presentation'
      type: 'presentation'
    values:
      navigationKey: presentation
      breadcrumb: true
      layout: 'page-side-navigation'
      include-in-nav: true
      subheadline: 'Présentation'
      header:
        image_fullwidth: 'cc2920-2018-06-24.jpg'
  - 
    scope: 
      path: '_prix'
      type: 'prix'
    values:
      navigationKey: prix
      breadcrumb: true
      layout: 'page-fullwidth'
      subheadline: 'Prix et mérites'
      header:
        image_fullwidth: 'cc2920-2018-06-24.jpg'
  - 
    scope: 
      path: '_ressources'
      type: 'ressources'
    values:
      navigationKey: ressources
      breadcrumb: true
      layout: 'page-fullwidth'
      subheadline: 'Ressources'
      header:
        image_fullwidth: 'expedition-foret.jpg'

#       _   __            _             __  _
#      / | / /___ __   __(_)___ _____ _/ /_(_)___  ____
#     /  |/ / __ `/ | / / / __ `/ __ `/ __/ / __ \/ __ \
#    / /|  / /_/ /| |/ / / /_/ / /_/ / /_/ / /_/ / / / /
#   /_/ |_/\__,_/ |___/_/\__, /\__,_/\__/_/\____/_/ /_/
#                       /____/
#
#  Open _data/navigation.yml to adjust the left and right topbar navigation
#



#     _____ __________
#    / ___// ____/ __ \
#    \__ \/ __/ / / / /
#   ___/ / /___/ /_/ /
#  /____/_____/\____/    Verify Website to Webmaster Tools

google_site_verification        : '00000'
bing_webmastertools_id          : '00000'
# yandex_site_verification      : ''
# alexa_verify_id               : ''




#       ______                __                __
#      / ____/___ _________  / /_  ____  ____  / /__
#     / /_  / __ `/ ___/ _ \/ __ \/ __ \/ __ \/ //_/
#    / __/ / /_/ / /__/  __/ /_/ / /_/ / /_/ / ,<
#   /_/    \__,_/\___/\___/_.___/\____/\____/_/|_|      Facebook-Optimization › http://j.mp/fb_optimize

og_image                             : ''
og_locale                            : 'fr_CA'
og_type                              : 'website'


#      _____            _       __   __  ___         ___
#     / ___/____  _____(_)___ _/ /  /  |/  /__  ____/ (_)___ _
#     \__ \/ __ \/ ___/ / __ `/ /  / /|_/ / _ \/ __  / / __ `/
#    ___/ / /_/ / /__/ / /_/ / /  / /  / /  __/ /_/ / / /_/ /
#   /____/\____/\___/_/\__,_/_/  /_/  /_/\___/\__,_/_/\__,_/
#
#  Open _data/socialmedia.yml to adjust the left and right topbar navigation
#

# socialmedia:
#     twitter   : sinedbo
#     facebook  : sinedbo.media



#      _____
#     / ___/____ ___________
#     \__ \/ __ `/ ___/ ___/
#    ___/ / /_/ (__  |__  )     More › http://sass-lang.com/
#   /____/\__,_/____/____/      More › http://jekyllrb.com/docs/assets/#sassscss
#

sass:
    sass_dir : _sass
    style    : :compressed


#       ___                __      __  _
#      /   |  ____  ____ _/ /_  __/ /_(_)_________
#     / /| | / __ \/ __ `/ / / / / __/ / ___/ ___/
#    / ___ |/ / / / /_/ / / /_/ / /_/ / /__(__  )
#   /_/  |_/_/ /_/\__,_/_/\__, /\__/_/\___/____/      https://www.google.com/analytics/
#                        /____/
#
# used in _includes/footer_scripts

# google_analytics_tracking_id:


