- menu_name: "Communication"

- name: "Nous rejoindre"
  url: "/information/comment-nous-rejoindre/"
  class: icon-message
  title: "Nous rejoindre"

- name: "Les messages de la semaine"
  url: "/communications"
  class: icon-mail
  title: "Les messages de la semaine"

- name: Groupe Facebook
  url: https://www.facebook.com/groups/cc2920Gatineau
  class: icon-facebook
  title: "Groupe Facebook des membres du CC2920"

# - name: Groupe Facebook des anciens 
#   url: https://www.facebook.com/groups/cc2920Gatineau
#   class: icon-facebook
#   title: "Groupe Facebook officielle des anciens membres et cadets du CC2920"